### ISSUE TITLE
Creacion de mockups

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#1]
Crear mockups, de acuerdo a la reunión sostenida con el cliente, del área de ingreso de datos generales del encuestado y la institución a la cual pertenece.

Items a evaluar:

- [ ] Una pregunta por vista

- [ ] Debe ser de tamaño grande el formulario, para que pueda ser leído por personas con 
        discapacidad visual parcial (bajo campo visual).

- [ ] El mockup debe contener indicación de los controles a utilizar en el maquetado en HTML 5.

- [ ] Software a utilizar Balsamic.

**Comment by mardurango** [comment]
[mockuts de datos personales.pdf](https://github.com/ojsilvera/unicornioines/files/3580075/mockuts.de.datos.personales.pdf)
