### ISSUE TITLE
Creación de mockups

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#2]
Crear mockups, de acuerdo a la reunión sostenida con el cliente, del área de administrador de datos generales del encuestado y la institución a la cual pertenece.

Ítems a evaluar:
El mockup debe contener indicación de los controles a utilizar en el maquetado en HTML 5.
Software a utilizar Balsamic.
El mockup muestra de manera clara la disposición de los elementos en la pantalla del dashboard del administrador
El área administración posee una vista de logeo.
El área de administración posee una vista de mantenimiento de usuarios.
El área de administración posee una vista de mantenimiento de encuesta.
El área de administración posee una vista de reportes.

**Comment by johngoez1803** [comment]
[Mockups.zip](https://github.com/ojsilvera/unicornioines/files/3580062/Mockups.zip)
