### ISSUE TITLE
Desarrollar Mockup de la encuetas segun el factor indicado

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#30]
Desarrollar en balsamic el mockup de las vistas de los factores del 6 al 12.

**Comment by johngoez1803** [comment]
creacion del mockup del factor 6 al 12

**Comment by johngoez1803** [comment]
[mockuts encuesta estudiante.pdf](https://github.com/ojsilvera/unicornioines/files/3597899/mockuts.encuesta.estudiante.pdf)
