### ISSUE TITLE
Desarrollo de la encuesta para levantamiento de información. 

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#46]
Anclar los formatos de encuesta utilizados para la reunión con el cliente.

**Comment by rigo7910** [comment]
¿Cuál es la Actividad Económica de su Empresa?

¿Qué Requiere su Empresa, un aplicativo web, una app o un sistema de información?

¿Se ha implementado anteriormente algún aplicativo parecido?

¿Qué problemas debe solucionar el aplicativo web?

¿Cuántos tipos de usuarios usarán el aplicativo web? 
	
¿Tienen los usuarios experiencia en este tipo de aplicaciones? 
	
Hay aplicaciones/sistemas relevantes a tener en cuenta en nuestro Sistema 
	
Cuáles son las expectativas de usabilidad del Producto? 
	
¿Cuáles son las expectativas de formación a usuarios para el uso del aplicativo? 
	
Qué tipo de ayuda requerirá el usuario (ayuda online,…)?

¿Cuáles son sus expectativas en cuanto a fiabilidad del sistema? 
	
¿Cuáles son sus expectativas en cuanto a rendimiento del sistema?
