### ISSUE TITLE
Desarrollo de mockups

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#5]
Desarrollar el mockups en balsamic de las vistas a maquetar en html, correspondiente a la identificacion del usuario que va a tomar la encuesta, junto a los datos de la institución a la cual pertenece, para tener una idea general de como se desarrollara el flujo de la aplicación en cuanto al desarrollo de la encuesta.

**Comment by mardurango** [comment]
[mockuts de datos personales.pdf](https://github.com/ojsilvera/unicornioines/files/3575876/mockuts.de.datos.personales.pdf)
