### ISSUE TITLE
Carta de inicio de proyecto

### ISSUE THREAD

**Issue by ojsilvera** [ojsilvera/unicornioines#53]
Evidencia de desarrollo a fundación unicornio, por medio de carta membreteada y firmada donde conste el desarrollo del proceso de negociación, donde se vea claramente la puesta en marcha del ciclo de desarrollo.

**Comment by rigo7910** [comment]
![Carta Fundacion Unicornio](https://user-images.githubusercontent.com/50636984/64885588-2b9a1700-d62a-11e9-86a9-153d5191ed1d.jpg)
